
query MyQuery($limit: Int!, $offset: Int!) {
  notifications:notificationNotifications(
    limit: $limit
    orderBy: { createdAt: DESC }
    offset: $offset
  ) {
    payload
    createdAt
    message
    title
    type
    isSeen
  }
}