query entities(
	$filter: EntitiesEntitiesBoolExp
	$order: [EntitiesEntitiesOrderBy!]
	$limit: Int
	$offset: Int
) {
	entity: entitiesEntities(
		where: $filter
		orderBy: $order
		limit: $limit
		offset: $offset
	) {
		id
		organizationLegalName
		contactEmail
		contactPersonName
		status
		contactPersonAltPhone
		location
		tinNumberUrl
		tinNumber
		businessLicenseUrl
		paymentMethod
		contactPersonPhone
		places {
			id
			name
			featuredMedia
			light_logo {
				id
				url
			}
			type
		}
	}
	total: entitiesEntitiesAggregate(where: $filter) {
		aggregate {
			count
		}
	}
	all: entitiesEntitiesAggregate {
		aggregate {
			count
		}
	}
	active: entitiesEntitiesAggregate(where: { status: { _eq: ACTIVE } }) {
		aggregate {
			count
		}
	}
	pending: entitiesEntitiesAggregate(where: { status: { _eq: PENDING } }) {
		aggregate {
			count
		}
	}
	closed: entitiesEntitiesAggregate(where: { status: { _eq: CLOSED } }) {
		aggregate {
			count
		}
	}
}
