query getDrinks(
  $filter: BasicsDrinksBoolExp
  $order: [BasicsDrinksOrderBy!]
  $limit: Int
  $offset: Int
) {
  basicsDrinks(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ) {
    id
    title
    price
    title
    description
    media {
      url
    }
  }
  basicsDrinksAggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
