query MyQuery($filter: UsersUsersBoolExp!, $limit: Int, $offset: Int) {
  usersUsers(
    where: $filter
    orderBy: { id: DESC }
    limit: $limit
    offset: $offset
  ) {
    fullName
    id
    status
    createdAt
    email
    photoUrl
    phoneNumber
    userRoles {
      userRole {
        value
      }
    }
  }
  usersUsersAggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
