query getInvoice($filter: bigint!) {
	billingsInvoicesByPk(id: $filter) {
		withHolding
		vat
		transactionId
		total
		subTotal
		startDate
		pricingPlanFrequencyPriceId
		reason
		invoiceNumber
		payment {
			id
			entity {
				organizationLegalName
				tinNumber
				contactPersonAltPhone
				contactPersonName
				contactPersonPhone
				contactEmail
				area {
					name
				}
				city {
					name
				}
			}
			paymentDate
			recieptUrl
			transactionNote
			paymentMethod
			pricing_plan_frequency {
				id
				price
				pricingPlan {
					title
					description
				}
				frequency
			}
		}
	}
}
