query billingsInvoice(
	$filter: BillingsInvoicesBoolExp
	$order: [BillingsInvoicesOrderBy!]
	$limit: Int
	$offset: Int
) {
	invoices: billingsInvoices(
		where: $filter
		orderBy: $order
		limit: $limit
		offset: $offset
	) {
		id
		payment {
			paymentMethod
			billing_address {
				place {
					id
					name
				}
			}
			total
			paymentDate
			pricing_plan_frequency {
				pricingPlan {
					description
					title
				}
				price
			}
			subscription_plans {
				id
			}
		}
	}
	length: billingsInvoicesAggregate(where: $filter) {
		aggregate {
			count
		}
	}
}
