query placeMedias(
  $filter: PlaceMediasBoolExp
  $order: [PlaceMediasOrderBy!]
  $limit: Int
  $offset: Int
) {
  placeMedias(where: $filter, orderBy: $order, limit: $limit, offset: $offset) {
    id
    isImage
    media {
      url
    }
  }
}
