query pricingPlans($id: bigint!) {
	billingsPricingPlansByPk(id: $id) {
		id
		isVisible
		description
		title
		type
		rank
		pricing_plan_frequencies {
			id
			price
			frequency
			items: pricing_plan_frequency_items {
				id
				item {
					title
					rules
					name
					itemType
					description
				}
			}
		}
		pricing_plan_features {
			id
			feature {
				title
				description
				id
			}
		}
	}
}
