query getReviewAd($id: bigint!) {
  reviewAdsByPk(id: $id) {
    id
    slogan
    startDate
    endDate
    isCurrentlyOpen
    review_ad_medias {
      media {
        id
        url
      }
    }
    review {
      id
      title
      description
      place {
        id
        name
        light_logo {
          url
        }
      }
    }
  }
}
