query getReviewAds($filter: ReviewAdsBoolExp) {
  reviewAds(where: $filter) {
    id
    slogan
    startDate
    endDate
    isCurrentlyOpen
    review_ad_medias {
      media {
        id
        url
      }
    }

    review {
      id
      title
      description
      place {
        id
        name
        type

        light_logo {
          url
        }
      }
    }
  }
}
