query getReview($id: bigint!) {
  reviewsByPk(id: $id) {
    id
    title
    youtubeVideoUrl
    tiktokUrl
    instagramUrl
    reviewedBy

    description
    view_count
    placeLocationId
    description

    # service rating
    place_sheger_review {
      comment
      rate
      place_sheger_review_by_services {
        rate
        reviewCategoryId
        review_category {
          id
          name
          type
          icon {
            lightIconUrl
          }
        }
      }
    }
    # place
    place {
      shegerRecommendationId
      id

      type

      status
      name
      dark_logo {
        url
      }
      light_logo {
        url
      }
      featuredReviewMediaUrl {
        url
      }
      # locations
      placeLocations {
        id
        location
        isMainLocation

        area {
          name
        }
        city {
          name
        }
      }
    }

    # tags
    review_tags {
      tag {
        id
        title
        icon {
          darkIconUrl
          lightIconUrl
        }
      }
    }

    # review aggregate
    review_aggregate_summary {
      avgRating
      sumLikes
    }

    reviewAggregate: reviewReviewsAggregate {
      aggregate {
        count
      }
    }
    featured_image {
      url
      id
    }
    # medias
    review_medias {
      id
      media {
        url
      }
    }

    # review menu
    menu_reviews {
      id
      menu {
        id
        price
        sides
        timeToPrepare
        title
        name: title
        isHouseSpecial
        isFeatured
        description
        type
        updatedAt
        menuTags {
          id
          tag {
            iconId
            title
            id
          }
        }
        media {
          url
        }
        menuMedias {
          media {
            url
          }
        }

        last_updated_menus(
          orderBy: [{ lastUpdate: DESC_NULLS_LAST }]
          limit: 1
        ) {
          id
          lastUpdate
        }
      }
    }

    # review drink
    review_drink {
      id
      drink {
        description
        id
        image
        price
        title
        media {
          url
        }
      }
    }
  }
}
