query getReviews(
  $filter: ReviewsBoolExp
  $order: [ReviewsOrderBy!]
  $limit: Int
  $offset: Int
) {
  reviews(where: $filter, orderBy: $order, limit: $limit, offset: $offset) {
    id
    title
    reviewedBy
    updatedAt

    # review place
    place {
      id
      name
      status
      type
      light_logo {
        url
      }
    }

    # review tags
    review_tags {
      id
      tag {
        id
        title
      }
    }

    # menu reviews
    menu_reviews {
      menu {
        id
        title
      }
    }
    # review aggregate
    review_aggregate_summary {
      avgRating
      sumLikes
    }
    reviewAggregate: reviewReviewsAggregate {
      aggregate {
        count
      }
    }

    # review featured media

    featured_image {
      url
    }
    # review medias

    review_medias {
      media {
        url
      }
    }
  }

  # Review aggregate

  reviewsAggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
