query billingsPaymentsItem($filter: bigint!) {
	billingsPaymentsByPk(id: $filter) {
		id
		entity {
			id
			organizationLegalName
			tinNumber
			contactPersonAltPhone
			contactPersonName
			contactPersonPhone
			contactEmail
			area {
				name
			}
			city {
				name
			}
		}
		subtotal
		total
		transactionId
		vat
		paymentDate
		paymentStatus
		isVerified
		isDeclined
		recieptUrl
		transactionNote
		verifiedBy
		vat
		paymentMethod
		withHolding
		pricing_plan_frequency {
			id
			price
			pricingPlan {
				title
				description
			}
			frequency
		}
		subscription_plans {
			id
		}
	}
}
