query billingsPaymentsItem($filter: bigint!) {
	billingsPaymentsByPk(id: $filter) {
		billingId
		id
		billing_address {
			place {
				id
				name
				contactAltPhoneNumber
				contactPhoneNumber
				contactEmail
			}
			id
		}
		subtotal
		total
		transactionId
		vat
		paymentDate
		paymentStatus
		isVerified
		isDeclined
		recieptUrl
		transactionNote
		verifiedBy
		vat
		paymentMethod
		withHolding
		pricing_plan_frequency {
			id
			price
			pricingPlan {
				title
				description
			}
			frequency
		}
		subscription_plans {
			id
		}
	}
}
