query priceCalculator($filter: billingsPricingPlanPriceCalculatorArgs!) {
	price: billingsPricingPlanPriceCalculator(args: $filter) {
		deduction
		remainingBalance
		subtotal
		vat
		total
		withHolding
	}
}
