query getCategories(
  $filter: BasicsCategoriesBoolExp
  $order: [BasicsCategoriesOrderBy!]
  $limit: Int
  $offset: Int
) {
  basicsCategories(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ) {
    id
    type
    title
    name: title
    placesAggregate {
      aggregate {
        count
      }
    }

    menusAggregate {
      aggregate {
        count
      }
    }
    icon {
      lightIconUrl
    }
  }
}
