query(
  $filter: PortfoliosBoolExp,
  $order: [PortfoliosOrderBy!],
  $limit: Int,
  $offset: Int,
){
  portfolios(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ){
    description
    id
    title
    date
    portfolioMedias{
      media{
        url
      }
    }
  }
}