query getPlaceAmenities(
  $filter: PlaceAmenitiesBoolExp
  $order: [PlaceAmenitiesOrderBy!]
  $limit: Int
  $offset: Int
) {
  placeAmenities(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ) {
    id
    amenityId
    description
    amenity {
      title
      id
      description
      icon {
        id
        darkIconUrl
        lightIconUrl
      }
    }
    placeAmenityResources {
      media {
        url
        id
      }
    }
  }
  # aggregate
  placeAmenitiesAggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
