query(
  $filter: PlaceMediasBoolExp,
  $order: [PlaceMediasOrderBy!],
  $limit: Int,
  $offset: Int,
){
  placeMedias(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ){
  	id
    media{
      url
    }
  }
}