query getPlacesPortfolios(
  $filter: PortfoliosBoolExp
  $order: [PortfoliosOrderBy!]
  $limit: Int
  $offset: Int
) {
  portfolios(where: $filter, orderBy: $order, limit: $limit, offset: $offset) {
    id
    title
    date
    portfolioMedias {
      media {
        url
      }
    }
    placeId
  }
}
