query getPlace($id: bigint!) {
  place: placesByPk(id: $id) {
    open_hours {
      day
      from
      to
      reason
      status
      placeId
      __typename
    }
    close_hours{
    date
    from
    to
    reason
    }
    id
    name
    entitiyId
    light_logo {
      url
    }
    view_count
    status
    cousins
    description
    type
    categoryId
    contactEmail
    contactWebsite
    contactPhoneNumber
    contactAltPhoneNumber
    youtubeVideoUrl
    place_aggregate_summary {
      minDishPrice
      maxDishPrice
    }
    offerTakeouts
    orderPhoneNumber1
    orderPhoneNumber2
    featured_medias {
      id
      url
    }
    placeMedias {
      id
      isImage
      media {
        url
      }
    }
    placeSocialMedias {
      id
      url
      socialMedia {
        name
        order
      }
    }
    featuredReviewMediaUrl {
      url
    }
    shegerRecommendationId
    shegerRecommendation {
      id
      title
      shegerRecommendationBadge {
        url
      }
      badge
      description
    }
    reviews {
      id
      title
      youtubeVideoUrl
    }
    placeAmbiances {
      id
      ambiance {
        icon {
          lightIconUrl
          darkIconUrl
        }
        id
        title
      }
    }
    placeTags {
      tagId
      tag {
        id
        title
        icon {
          lightIconUrl
          darkIconUrl
        }
      }
    }
    place_cousins {
      id
      cousinId
      cousin {
        id
        title
      }
    }
    placeLocations {
      id
      location
      isMainLocation
      area {
        name
      }
      city {
        name
      }
    }
    placeAmenities {
      id
      amenity {
        id
        icon {
          lightIconUrl
          darkIconUrl
        }
        title
      }
    }
    placeSocialMedias {
      url
      socialMedia {
        icon {
          lightIconUrl
        }
        url
        order
        name
        id
      }
    }
    featured_places {
      id
      startDate
      endDate
      isActive
      type
    }
    place_aggregate_summary {
      avgDishPrice
      avgRating
      sumLikes
      minDishPrice
      maxDishPrice
    }
    placeReviewsAggregate {
      aggregate {
        count
      }
    }
    menus(
      where: {isHouseSpecial: {_eq: true}}
      orderBy: [{createdAt: DESC}]
      limit: 1
      offset: 0
    ) {
      id
      title
      updatedAt
      isHouseSpecial
      timeToPrepare
      media {
        url
      }
      menuTags {
        tag {
          title
          icon {
            lightIconUrl
            darkIconUrl
          }
        }
      }
    }
    cousins
  }
}