query getPlace($id: bigint!, $include: Boolean = false) {
  place: placesByPk(id: $id) {
    id
    name
    view_count
    status
    cousins

    # contact us
    contactEmail
    contactWebsite
    contactPhoneNumber
    contactAltPhoneNumber

    # place aggregate
    place_aggregate_summary {
      minDishPrice
      maxDishPrice
    }

    # takeout
    offerTakeouts
    orderPhoneNumber1
    orderPhoneNumber2

    # place medias
    placeMedias {
      media {
        url
      }
    }
    # place social media
    placeSocialMedias {
      id
      url
      socialMedia {
        name
        order
      }
    }

    # video  media

    featuredReviewMediaUrl {
      url
    }

    # tags
    placeTags {
      tag {
        title
        # icon {
        #   lightIconUrl
        #   darkIconUrl
        # }
      }
    }

    # locations
    placeLocations {
      id
      location
      isMainLocation
      area {
        name
      }
      city {
        name
      }
    }

    # amenities
    placeAmenities {
      id
      amenity {
        id
        # icon {
        #   lightIconUrl
        #   darkIconUrl
        # }
        title
      }
    }

    # social media
    placeSocialMedias {
      url
      socialMedia {
        url
        order
        name
        id
      }
    }

    # place aggregate
    place_aggregate_summary {
      avgDishPrice
      avgRating
      sumLikes
      minDishPrice
      maxDishPrice
    }

    # review aggregate
    placeReviewsAggregate {
      aggregate {
        count
      }
    }

    # shegere recommendations
    shegerRecommendationId
    shegerRecommendation {
      id
      title
      shegerRecommendationBadge {
        url
      }
      badge
      description
    }

    # featured place
    featured_places {
      startDate
      endDate
      isActive
      type
    }

    # special menu
    menus(
      where: { isHouseSpecial: { _eq: true } }
      orderBy: [{ createdAt: DESC }]
      limit: 1
      offset: 0
    ) {
      id

      title
      updatedAt
      isHouseSpecial
      timeToPrepare
      media {
        url
      }
      menuTags {
        tag {
          title
          # icon {
          #   lightIconUrl
          #   darkIconUrl
          # }
        }
      }
    }
  }
}
