query(
  $filter: MenuTypesBoolExp,
  $order: [MenuTypesOrderBy!],
  $limit: Int,
  $offset: Int,
){
	menuTypes(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ){
    value
  }
}