query getMenu($id: bigint!) {
  menu: menusByPk(id: $id) {
    id
    price
    sides
    timeToPrepare
    ingridients
    title
    categoryId
    type
    updatedAt

    # featured image
    media {
      url
    }
    menuTags {
      id
      tag {
        iconId
        title
        id
      }
    }
    media {
      url
    }
    menuMedias {
      id
      media {
        url
      }
    }
    isHouseSpecial
    isFeatured
    description

    place {
      id
      name
      type
    }
  }
}
