query getMenus(
  $filter: MenusBoolExp
  $order: [MenusOrderBy!]
  $limit: Int
  $offset: Int
) {
  menus(where: $filter, orderBy: $order, limit: $limit, offset: $offset) {
    id
    id
    price
    sides
    timeToPrepare
    title
    type
    ingridients
    updatedAt
    menuTags {
      id
      tag {
        iconId
        title
        id
      }
    }
    media {
      url
    }
    menuMedias {
      media {
        url
      }
    }
    isHouseSpecial
    isFeatured
    description

    place {
      id
      name
      type
      # logo {
      #   id
      #   url
      # }
    }

    # reviews
    menu_reviews {
      id
      review {
        id
        title
        placeId
      }
    }

    # last update
    last_updated_menus(orderBy: [{ lastUpdate: DESC_NULLS_LAST }], limit: 1) {
      id
      lastUpdate
    }
  }
  # menu aggregates
  menusAggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
