query getPlaceAd($id: bigint!) {
  placeAdsByPk(id: $id) {
    id
    media {
      url
    }
    place_ad_medias {
      media {
        id
        url
      }
    }
    description
    slogan
    startDate
    endDate
    place {
      id
      name
      type

      contactAltPhoneNumber
      contactEmail
      contactWebsite
      light_logo {
        url
      }
    }
  }
}
