query getPlaceAds($filter: PlaceAdsBoolExp) {
  placeAds(where: $filter) {
    id
    media {
      url
    }
    place_ad_medias {
      media {
        id
        url
      }
    }
    description
    slogan
    startDate
    endDate
    place {
      light_logo {
        url
      }
      type
      name
      id
      contactAltPhoneNumber
      contactEmail
      contactWebsite
      light_logo {
        url
      }
    }
  }
}
