query getPlaceAds($filter: PlaceAdsBoolExp) {
  placeAds(where: $filter) {
    id
    media {
      url
    }
    description
    slogan
    startDate
    endDate
    place {
      type
      name
      id
      contactAltPhoneNumber
      contactEmail
      contactWebsite
    }
  }
}
