query getAmenities(
  $filter: BasicsAmenitiesBoolExp
  $order: [BasicsAmenitiesOrderBy!]
  $limit: Int
  $offset: Int
) {
  basicsAmenities(
    where: $filter
    orderBy: $order
    limit: $limit
    offset: $offset
  ) {
    id
    title
    name: title
    icon {
      lightIconUrl
      darkIconUrl
    }
  }
}
